# Generated by Django 4.2.30 on 2026-06-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='replied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='reply',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='accent_brand_color',
            field=models.CharField(default='#D4A520', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='momo_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='momo_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payout_method',
            field=models.CharField(default='MOMO', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='primary_brand_color',
            field=models.CharField(default='#1B5E3F', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='self_shipping_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='subscription_tier',
            field=models.CharField(default='Standard', max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='tin',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='pages.shipment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
