# Generated by Django 4.2.30 on 2026-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_review_replied_at_review_reply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='vendor_documents/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='business_document_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
